In [2]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import io

In [9]:
# File to Load
sales_data_to_load = "data/sales_info.csv"
zip_data_to_load = "data/zipcode_demo.csv"

# Read the Sales and ZipCode Data
sales_data_df = pd.read_csv(sales_data_to_load)
zip_data_df = pd.read_csv(zip_data_to_load)

In [9]:
sales_data_df.dtypes

CustomerID      int64
ZipCode        object
State          object
Country        object
LOB            object
Market         object
OrderID         int64
OrderDate      object
Quantity        int64
UnitPrice     float64
Total         float64
SKU            object
Title          object
Brand          object
dtype: object

In [15]:
zip_data_df.dtypes

Unnamed: 0       int64
ZipCode         object
lat            float64
lng            float64
city            object
state_id        object
state_name      object
zcta              bool
population       int64
density        float64
county_fips      int64
dtype: object

In [10]:
zip_data_df['ZipCode'] = str('ZipCode')

In [15]:
# Combine the data into a single dataset
sports_data_df = pd.merge(sales_data_df, zip_data_df, how="left", on=["ZipCode"])

# Display the data table for preview
sports_data_df.head(5)

,Unnamed: 0_x,CustomerID,ZipCode,State,Country,LOB,Market,OrderID,OrderDate,Quantity,...,Unnamed: 0_y,lat,lng,city,state_id,state_name,zcta,population,density,county_fips
0,0,10012,49649,MI,US,Salvage,eBay,4468639,2021-04-29,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,10012,49649,MI,US,Salvage,eBay,4468548,2021-04-29,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10012,49649,MI,US,Salvage,eBay,4471261,2021-04-30,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10012,49649,MI,US,Salvage,eBay,4468548,2021-04-29,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,24012,68713,NE,US,Salvage,PSN-Web,4758999,2021-09-07,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN